import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Sougata",
      email: "admin@example.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
        name: "John",
        email: "user@example.com",
        password: bcrypt.hashSync("1234", 8),
        isAdmin: false,
      },
  ],
  products: [
    {
      // _id: "1",
      name: "Nike Slim Shirt",
      category: "shirts",
      images: "/image/p6.jpg",
      price: 2199,
      countInStock: 10,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      // _id: "2",
      name: "Lacoste free Shirt",
      category: "shirts",
      images: "/image/p1.jpg",
      price: 799,
      countInStock: 15,
      brand: "Lacoste",
      rating: 4.0,
      numReviews: 14,
      description: "high quality product",
    },
    {
      // _id: "3",
      name: "Turtel Slim Shirt",
      category: "shirts",
      images: "/image/p3.jpg",
      price: 999,
      countInStock: 8,
      brand: "Turtel",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      // _id: "4",
      name: "Denim Slim Shirt",
      category: "shirts",
      images: "/image/p4.jpg",
      price: 1999,
      countInStock: 0,
      brand: "Denim",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      // _id: "5",
      name: "Leecooper Slim Shirt",
      category: "shirts",
      images: "/image/p5.jpg",
      price: 1499,
      countInStock: 20,
      brand: "leecooper",
      rating: 4.2,
      numReviews: 18,
      description: "high quality product",
    },
    {
      // _id: "6",
      name: "Flying Machine Shirt",
      category: "shirts",
      images: "/image/p2.jpg",
      price: 1299,
      countInStock: 5,
      brand: "flying",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
  ],
};

export default data;
